version: '3.8'
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: default_db_name
      POSTGRES_USER: default_user
      POSTGRES_PASSWORD: default_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: